"""
Django settings for hotel_prj project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from urllib.parse import parse_qs, unquote, urlparse

# Load environment variables early so they are available for configuration
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7rwndw#hwmeti5^2j-8rw!j0b5lke#pmws)a7e^399nrmglpfr'

# SECURITY WARNING: don't run with debug turned on in production!
# Controlled via env so local dev can set DEBUG=True without code changes.
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# Comma separated list, defaults to allow all so dev keeps working.
ALLOWED_HOSTS = [host.strip() for host in os.getenv("ALLOWED_HOSTS", "*").split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hotel_app',
    'accounts'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hotel_prj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hotel_prj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


def _getenv(*names, default=None):
    for name in names:
        value = os.getenv(name)
        if value:
            return value
    return default


def _postgres_config_from_url(database_url):
    parsed = urlparse(database_url)
    if parsed.scheme not in {"postgres", "postgresql"}:
        return None

    name = parsed.path.lstrip("/")
    if not name:
        return None

    config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': name,
        'USER': unquote(parsed.username or ''),
        'PASSWORD': unquote(parsed.password or ''),
        'HOST': parsed.hostname or '',
        'PORT': str(parsed.port or '5432'),
    }

    options = {key: values[-1] for key, values in parse_qs(parsed.query).items() if values}
    if options:
        config['OPTIONS'] = options

    return config


def _database_config_from_env():
    database_url = _getenv("DATABASE_URL", "POSTGRES_URL", "POSTGRESQL_URL")
    if database_url:
        config = _postgres_config_from_url(database_url)
        if config:
            return {'default': config}

    # Legacy MYSQL_* names are still accepted during the transition so existing
    # deployments keep working until the environment variables are renamed.
    host = _getenv("POSTGRES_HOST", "PGHOST", "MYSQL_HOST")
    if host:
        config = {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _getenv("POSTGRES_DB", "POSTGRES_DATABASE", "PGDATABASE", "MYSQL_DATABASE", default='postgres'),
            'USER': _getenv("POSTGRES_USER", "PGUSER", "MYSQL_USER", default='postgres'),
            'PASSWORD': _getenv("POSTGRES_PASSWORD", "PGPASSWORD", "MYSQL_PASSWORD", default=''),
            'HOST': host,
            'PORT': _getenv("POSTGRES_PORT", "PGPORT", "MYSQL_PORT", default='5432'),
        }

        sslmode = _getenv("POSTGRES_SSLMODE", "PGSSLMODE")
        if sslmode:
            config['OPTIONS'] = {'sslmode': sslmode}

        return {'default': config}

    return {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


DATABASES = _database_config_from_env()

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / 'hotel_app/static']


STATIC_ROOT = BASE_DIR / 'staticfiles'
# Use hashed, compressed files for production; simpler storage in debug to avoid
# manifest errors during local development.
STATICFILES_STORAGE = (
    'django.contrib.staticfiles.storage.StaticFilesStorage'
    if DEBUG
    else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

host_user = os.getenv("EMAIL_USER")
host_pass = os.getenv("EMAIL_PASSWORD")

# Email configuration: prefer SMTP when credentials are present, fall back to console in dev
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend" if host_user and host_pass else "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = host_user
EMAIL_HOST_PASSWORD = host_pass
