"""
Django settings for hotel_prj project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from dotenv import load_dotenv

# Load environment variables early so they are available for configuration.
# override=True ensures edits to .env take effect on the next process start
# (otherwise stale OS-level vars from a previous run silently win).
load_dotenv(override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Loaded from .env. Fail loudly if missing — never fall back to a hardcoded key.
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY is not set. Add it to your .env file or environment variables.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# Comma separated list; in DEBUG defaults to localhost, in prod must be set explicitly.
_default_hosts = "localhost,127.0.0.1" if DEBUG else ""
ALLOWED_HOSTS = [
    host.strip() for host in os.getenv("ALLOWED_HOSTS", _default_hosts).split(",") if host.strip()
]
if not DEBUG and not ALLOWED_HOSTS:
    raise RuntimeError("ALLOWED_HOSTS must be set when DEBUG=False.")

# CSRF trusted origins (full scheme+host) — required for HTTPS POSTs on Vercel/Render etc.
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # required by allauth
    "django.contrib.sitemaps",  # /sitemap.xml
    "axes",
    # ---- django-allauth + Google social login ----
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    # ---- our apps ----
    "hotel_app",
    "accounts",
]

# allauth needs this. Single-site setup ⇒ id=1; allauth's migration seeds it.
SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # Stamp Cache-Control on /media/ responses so a CDN/browser can cache them.
    "hotel_app.middleware.MediaCacheMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # allauth requires its account middleware after the auth middleware.
    "allauth.account.middleware.AccountMiddleware",
    # AxesMiddleware must be last so it sees the final user state from auth middleware.
    "axes.middleware.AxesMiddleware",
]

# Auth backends — order matters:
# 1. axes guards brute-force attempts
# 2. our model backend handles email/password
# 3. allauth handles social (Google) + their own account flow
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
# Brute-force protection — locks (IP, username) after N consecutive failed
# logins. Honor AXES_ENABLED from env so you can disable it in dev without
# having to keep running `python manage.py axes_reset` while iterating on
# the auth flow.
AXES_ENABLED = os.getenv("AXES_ENABLED", "True").lower() == "true"
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]
AXES_RESET_ON_SUCCESS = True

ROOT_URLCONF = "hotel_prj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Why DIRS is non-empty: Django's app loader searches INSTALLED_APPS
        # in declaration order, so allauth (declared first) would win every
        # `account/*.html` template lookup. Listing our `accounts/templates`
        # here means Django checks it BEFORE walking the apps — our
        # password_reset/change/email overrides win cleanly.
        "DIRS": [BASE_DIR / "accounts" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hotel_prj.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


def _getenv(*names, default=None):
    for name in names:
        value = os.getenv(name)
        if value:
            return value
    return default


def _postgres_config_from_url(database_url):
    parsed = urlparse(database_url)
    if parsed.scheme not in {"postgres", "postgresql"}:
        return None

    name = parsed.path.lstrip("/")
    if not name:
        return None

    config = {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": name,
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "",
        "PORT": str(parsed.port or "5432"),
    }

    options = {key: values[-1] for key, values in parse_qs(parsed.query).items() if values}
    if options:
        config["OPTIONS"] = options

    return config


def _database_config_from_env():
    database_url = _getenv("DATABASE_URL", "POSTGRES_URL", "POSTGRESQL_URL")
    if database_url:
        config = _postgres_config_from_url(database_url)
        if config:
            return {"default": config}

    # Legacy MYSQL_* names are still accepted during the transition so existing
    # deployments keep working until the environment variables are renamed.
    host = _getenv("POSTGRES_HOST", "PGHOST", "MYSQL_HOST")
    if host:
        config = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _getenv(
                "POSTGRES_DB",
                "POSTGRES_DATABASE",
                "PGDATABASE",
                "MYSQL_DATABASE",
                default="postgres",
            ),
            "USER": _getenv("POSTGRES_USER", "PGUSER", "MYSQL_USER", default="postgres"),
            "PASSWORD": _getenv("POSTGRES_PASSWORD", "PGPASSWORD", "MYSQL_PASSWORD", default=""),
            "HOST": host,
            "PORT": _getenv("POSTGRES_PORT", "PGPORT", "MYSQL_PORT", default="5432"),
        }

        sslmode = _getenv("POSTGRES_SSLMODE", "PGSSLMODE")
        if sslmode:
            config["OPTIONS"] = {"sslmode": sslmode}

        return {"default": config}

    # SQLite fallback is for local dev only. In production we refuse to start
    # without an explicit DATABASE_URL to avoid silently writing to an ephemeral file.
    if not DEBUG:
        raise RuntimeError(
            "No DATABASE_URL / POSTGRES_* env vars set. "
            "Refusing to fall back to SQLite when DEBUG=False."
        )
    return {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


DATABASES = _database_config_from_env()

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [BASE_DIR / "hotel_app/static"]


STATIC_ROOT = BASE_DIR / "staticfiles"
# Storage backend:
#   - In dev (DEBUG=True): plain StaticFilesStorage — serves directly from
#     app `static/` dirs without needing collectstatic.
#   - In prod: CompressedStaticFilesStorage — WhiteNoise still compresses
#     + serves the files, but no manifest is required.
#
# We used to use CompressedManifestStaticFilesStorage which adds content-
# hash filenames for cache busting, but it crashes the entire app at runtime
# if the `staticfiles.json` manifest isn't bundled into the deployed Lambda
# (Vercel's @vercel/python builder doesn't include it by default). The
# Compressed variant has no manifest dependency so deployments are reliable.
STATICFILES_STORAGE = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"
    if DEBUG
    else "whitenoise.storage.CompressedStaticFilesStorage"
)
# WhiteNoise: cache hashed static files for 1 year — they have a content
# hash in the filename so changes invalidate themselves. Combined with a
# CDN (Cloudflare etc.) this means every CSS/JS/font is served from edge
# memory after the first visit per region.
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 365  # 1 year

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# Cache-Control header stamped on /media/ responses by our middleware
# (hot_app.middleware.MediaCacheMiddleware). 1 day is a reasonable balance:
# hotel photos rarely change, but vendors do occasionally replace them.
# A CDN in front (Cloudflare) honors this and serves from edge cache.
MEDIA_CACHE_MAX_AGE = 60 * 60 * 24  # 1 day


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

host_user = os.getenv("EMAIL_USER")
host_pass = os.getenv("EMAIL_PASSWORD")

# Email configuration: prefer SMTP when credentials are present, fall back to console in dev
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend"
    if host_user and host_pass
    else "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = "smtp.gmail.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = host_user
EMAIL_HOST_PASSWORD = host_pass


# ---- Cache backend ---------------------------------------------------------
# When REDIS_URL is set we use Django's built-in Redis backend (Django 4.0+
# ships it — no `django-redis` package needed). Otherwise we fall back to
# LocMemCache, which is per-process but completely free + zero setup. That's
# fine for single-worker dev; in prod under gunicorn with N workers you
# want Redis so they share state.
_redis_url = os.getenv("REDIS_URL", "")
if _redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _redis_url,
            "TIMEOUT": 300,  # default 5 min — individual cache.set calls override
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "noma-default",
            "TIMEOUT": 300,
        }
    }


# ---- django-allauth (Continue with Google) ----
# Email is the unique identifier (we already use it as the username).
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_EMAIL_REQUIRED = True  # required when login method is email
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"  # Google's email is already verified
ACCOUNT_USERNAME_REQUIRED = False  # use email as username
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_UNIQUE_EMAIL = True
LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
# Skip the "intermediate" allauth signup confirmation page after Google login —
# users land straight on the home page once OAuth succeeds.
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True  # one-click Google button (no confirm screen)
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
# Auto-link a Google login to any existing account with the same (verified)
# email. Without this, allauth shows the "3rdparty/signup" intermediate page
# whenever a Google sign-in matches a User that was originally created via
# our own email/password register flow. Google has already verified the
# address, so linking is safe.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
# Our adapter handles the case where the existing User has NO allauth
# EmailAddress row (created by our /account/register_page/ view directly).
SOCIALACCOUNT_ADAPTER = "accounts.adapters.AutoConnectByEmailAdapter"
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        # Credentials come from env; in dev you can also set them in the admin
        # under "Social applications" if you prefer the click-through UI.
        "APP": {
            "client_id": os.getenv("GOOGLE_OAUTH_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
}


# ---- Razorpay (test mode in dev) ----
# Use TEST keys (rzp_test_...) until you go live. KEY_ID is public (sent to
# the browser); KEY_SECRET signs server-side calls; WEBHOOK_SECRET verifies
# inbound events. Webhook secret is set per webhook in the Razorpay dashboard
# (Settings → Webhooks) — different from your API secret.
RAZORPAY_KEY_ID = os.getenv("RAZORPAY_KEY_ID", "")
RAZORPAY_KEY_SECRET = os.getenv("RAZORPAY_KEY_SECRET", "")
RAZORPAY_WEBHOOK_SECRET = os.getenv("RAZORPAY_WEBHOOK_SECRET", "")
RAZORPAY_CURRENCY = os.getenv("RAZORPAY_CURRENCY", "INR")
# Public site URL for building redirect targets after payment.
SITE_URL = os.getenv("SITE_URL", "http://127.0.0.1:8000")


# ---- Security hardening (active when DEBUG=False) ----
# Stays soft in dev so local http://127.0.0.1 keeps working.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30  # 30 days; bump to 1y once verified stable
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    X_FRAME_OPTIONS = "DENY"
    # Honor proxy headers from Vercel/Render so request.is_secure() is correct.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
