# Generated by Django 4.2 on 2025-07-18 04:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities_name', models.CharField(max_length=120)),
                ('icon', models.ImageField(upload_to='hotels')),
            ],
        ),
        migrations.CreateModel(
            name='hotel_owner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(upload_to='profile')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.IntegerField(blank=True, max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='hotel_vendor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ImageField(upload_to='profile')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.IntegerField(blank=True, max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.TextField(max_length=1200)),
                ('hotel_slug', models.SlugField(max_length=1200, unique=True)),
                ('hotel_price', models.FloatField()),
                ('hotel_offer_price', models.FloatField()),
                ('hotel_location', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('hotel_aminities', models.ManyToManyField(to='accounts.amenities')),
                ('hotel_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='accounts.hotel_vendor')),
            ],
        ),
        migrations.CreateModel(
            name='hotel_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=110)),
                ('manager_contact', models.CharField(max_length=110)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_manager', to='accounts.hotels')),
            ],
        ),
        migrations.CreateModel(
            name='hotel_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_images', to='accounts.hotels')),
            ],
        ),
    ]
