# Generated by Django 4.2 on 2025-07-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_owner',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel_vendor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
