# Generated by Django 4.2 on 2026-05-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_email',
            field=models.EmailField(db_index=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='customers',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='hotel_owner',
            name='otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='hotel_vendor',
            name='otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='hotel_name',
            field=models.CharField(db_index=True, max_length=191),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='customers',
            index=models.Index(fields=['hotel', 'start_date', 'end_date'], name='cust_hotel_dates_idx'),
        ),
    ]
