# Generated by Django 4.2 on 2025-07-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hotel_owner_is_verified_hotel_vendor_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_owner',
            name='otp',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
