# Generated by Django 4.2 on 2025-07-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_hotel_owner_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_vendor',
            name='otp',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
