# Generated by Django 4.2 on 2025-07-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hotel_vendor_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_owner',
            name='firstname',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='hotel_owner',
            name='lastname',
            field=models.CharField(max_length=28, null=True),
        ),
    ]
