# Generated by Django 4.2.30 on 2026-05-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hotels_rating_avg_hotels_rating_count_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_owner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
