# Generated by Django 4.2 on 2025-07-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hotel_owner_firstname_hotel_owner_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_owner',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel_vendor',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
