# Generated by Django 4.2.30 on 2026-05-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_hotel_owner_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('publish', 'Hotel publishing fee'), ('boost', 'Listing boost'), ('subscription', 'Monthly subscription'), ('other', 'Other')], default='publish', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (admin only).')),
                ('hotel', models.ForeignKey(blank=True, help_text='Optional — set when the charge is for a specific hotel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_charges', to='accounts.hotels')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='accounts.hotel_vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='vc_vendor_status_idx')],
            },
        ),
    ]
