# Generated by Django 4.2 on 2025-07-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_hotel_owner_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel_owner',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hotel_vendor',
            options={},
        ),
    ]
