# Generated by Django 4.2.30 on 2026-05-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vendorcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorcharge',
            name='due_date',
            field=models.DateField(blank=True, help_text='Pay-by date. Reminders start 5 days before; after grace expires, hotels are hidden.', null=True),
        ),
        migrations.AddField(
            model_name='vendorcharge',
            name='grace_days',
            field=models.PositiveSmallIntegerField(default=15, help_text='Days of grace after due_date before hotels get hidden.'),
        ),
        migrations.AddField(
            model_name='vendorcharge',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, help_text="Updated by the daily reminder command so we don't email twice in 24h.", null=True),
        ),
        migrations.AddIndex(
            model_name='vendorcharge',
            index=models.Index(fields=['status', 'due_date'], name='vc_status_due_idx'),
        ),
    ]
