# Generated by Django 4.2 on 2025-07-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_hotel_owner_options_alter_hotel_vendor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_vendor',
            name='business_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel_vendor',
            name='firstname',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='hotel_vendor',
            name='lastname',
            field=models.CharField(max_length=28, null=True),
        ),
    ]
