# Generated by Django 4.2.30 on 2026-05-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vendorcharge_due_date_vendorcharge_grace_days_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customers',
        ),
    ]
