# Generated by Django 4.2 on 2025-07-28 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_hotel_booking_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_fname', models.CharField(max_length=100)),
                ('customer_lname', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment', models.FloatField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to='accounts.hotels')),
            ],
        ),
    ]
