# Generated by Django 4.2.30 on 2026-06-14 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('tagline', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price_monthly_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_hotels', models.PositiveIntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('max_rooms_per_hotel', models.PositiveIntegerField(blank=True, null=True)),
                ('max_images_per_hotel', models.PositiveIntegerField(blank=True, null=True)),
                ('has_analytics', models.BooleanField(default=False)),
                ('has_featured_listing', models.BooleanField(default=False)),
                ('has_api_access', models.BooleanField(default=False)),
                ('has_priority_support', models.BooleanField(default=False)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=10, help_text='Platform cut per confirmed booking. Lower = better for the vendor.', max_digits=5)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order on /pricing/.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to retire a plan from sign-up.')),
                ('is_default', models.BooleanField(default=False, help_text='The plan new vendors land on. Exactly one row should have this.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'price_monthly_inr'],
            },
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled (ends at period end)'), ('expired', 'Expired')], default='active', max_length=16)),
                ('period_start', models.DateField(help_text='First day this billing cycle covers.')),
                ('period_end', models.DateField(help_text='Last day this billing cycle covers (inclusive).')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.plan')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.hotel_vendor')),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
                'indexes': [models.Index(fields=['vendor', 'status'], name='sub_vendor_status_idx'), models.Index(fields=['status', 'period_end'], name='sub_status_period_end_idx')],
            },
        ),
    ]
