# Generated by Django 4.2 on 2025-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_vendor',
            name='vendor_email',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='hotel_booking',
        ),
    ]
