# Generated by Django 4.2 on 2025-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_hotel_vendor_vendor_email_delete_hotel_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_vendor',
            name='email_token',
        ),
        migrations.AlterField(
            model_name='hotel_vendor',
            name='vendor_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
