# Generated by Django 4.2 on 2025-07-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_hotel_vendor_email_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_vendor',
            old_name='vendor_email',
            new_name='email_token',
        ),
    ]
