# Generated by Django 4.2 on 2025-07-29 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_vendor_email_hotel_vendor_email_token'),
    ]

    operations = [
    ]
