# Generated by Django 4.2 on 2025-07-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20250729_1341'),
    ]

    operations = [
    ]
