# Generated by Django 4.2 on 2025-08-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20250729_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='hotel_slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
